name: happyfinance_mobile
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.41.1

dependencies:
  bloc: ^9.2.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  file_picker: ^10.3.10
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  hive_ce_flutter: ^2.3.4
  image: ^4.7.2
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  json_annotation: ^4.10.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^6.0.2
  shimmer: ^3.0.0
  wechat_assets_picker: ^10.1.0

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  build_runner: ^2.11.1
  device_preview_plus: ^2.6.1
  envied_generator: ^1.3.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  hive_ce_generator: ^1.11.0
  json_serializable: ^6.12.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
